### ISSUE TITLE
Landing page for the platform

### ISSUE THREAD

**Issue by kostasgrevenitis** [c0c0n3/kitt4sme.live#312]

**Comment by kostasgrevenitis** [comment]
I already implemented a simple one

**Comment by RyanKelvinFord** [comment]
https://github.com/c0c0n3/kitt4sme.live/pull/325

Found an issue in the deployment i made it will now working when you load http://10.47.9.231/static-page/ (change the ip to kitt4sme.collab-cloud.eu/)

Just need PR to be merged first, and then we will change it so that it will load the page from the root kitt4sme.collab-cloud.eu/ and from static-page/
