### ISSUE TITLE
Get the update info from orion in the SADS online

### ISSUE THREAD

**Issue by souayb** [c0c0n3/kitt4sme.live#336]
### Describe the bug
The current status of SADS online update on the fixe time interval, which does not necessarily coincide with update in the context broker.

### Expected behavior
The SADS online solution is updated using the update info from the orion.

**Comment by c0c0n3** [comment]
@souayb you should change this line

- https://github.com/c0c0n3/kitt4sme.flaw-sleuth/blob/main/flawsleuth/timeseries.py#L31

to use the `fromDate` parameter instead:

- https://github.com/orchestracities/ngsi-timeseries-api/blob/master/specification/quantumleap.yml#L283C3-L283C11

**Comment by karikolehmainen** [comment]
What is the status of this video and can we close it as not relevant?

**Comment by c0c0n3** [comment]
@karikolehmainen @souayb this is still an issue I think, but it only affects the "online" (i.e. streaming) implementation. Since we decided the blessed implementation we'll adopt going forward until the end of the project is the "offline" (i.e. batch, see #368) one, we don't need to fix this issue. But we can leave it open as a reminder if @souayb decides to fix it in the future.

**Comment by karikolehmainen** [comment]
I propose to close it and reopen if necessary

                Kari Kolehmainen
                VTT
                tel.+358 40 533 0649
________________________________
